In [48]:
# Import Functions
import pandas as pd
import os
import time
import csv
import json
import fnmatch
import csv
import sqlalchemy as sql
import numpy as np
dbHost='mxnunx41'
dbPort='1521'
dbUser='lims'
dbPassword='Mumwit63'
dbName='hwi1'
dburl='oracle://'

In [49]:
# Default Parameters setting
with open('.//configFiles//BioRad.json', 'r') as f:
    config = json.load(f)
lab = config['lab']
analysis = config['analysis']
inst = config['inst']
mode = config['mode']
colsOrder=['Sample.Sample_Number', 'Test.Test_Number','Result.Name', 'Result.Entry', 'Result.Entered_By','Result.Instrument']

In [50]:
# get Data from DB
def getDataFromDB(sampleNumbersList):
    dburl = 'oracle://'+dbUser+':'+dbPassword+'@'+dbHost+':'+dbPort+'/'+dbName
    engine=sql.create_engine(dburl)
    resultdf=pd.DataFrame()
    sampleNumbrStr=(', '.join("'" + item + "'" for item in sampleNumbersList))
    queryText="SELECT sample_number, analysis, REPLICATE_COUNT,TEST_NUMBER FROM test"
    queryText=queryText+" WHERE SAMPLE_NUMBER IN ("+sampleNumbrStr+") AND analysis IN ('LSP-IQ125C')"
    conn = engine.connect()
    resultdf = pd.read_sql(queryText, engine)
    conn.close()
    return resultdf

In [51]:
#write the file
def writeFile(dframe,lab,inst,archDestination,importDest,datapath,fname):
    timestr = time.strftime("%Y%m%d%H%M%S")
    FileName = importDest + lab+'_'+inst+'_' + timestr + '.csv'
    dframe.to_csv(FileName, index=False, encoding="utf-8",quotechar='"',quoting=csv.QUOTE_NONNUMERIC) # write  out the file to be imported
    destination = archDestination + fname[:-4] + '.bak' # Backup the processed file
    os.rename(datapath, destination)
    time.sleep(1)

In [52]:
for eachlab in lab:
    print('Lab:'+eachlab)
    path= './/SampleFiles_Instruments//BioRad//'
    '''
    path='//mxns.loc//shares//NA-Instruments//Prod//'+eachlab+'//Import//'+inst+'//'
    archivedDestination='//mxns.loc//shares//NA-Instruments//Prod//'+eachlab+'//Import//'+inst+'//'
    if(mode=='T'):
        importDest='//mxns.loc//shares//NA-Instruments//Prod//'+eachlab+'//impf//testing//'
    else:
        importDest='//mxns.loc//shares//NA-Instruments//Prod//'+eachlab+'//impf//'
    if os.path.exists(path):
        pass
    else:
        os.makedirs(path)
    if os.path.exists(importDest):
        pass
    else:
        os.makedirs(importDest)
    '''
    files = os.listdir(path)
    for filename in files:
        if fnmatch.fnmatch(filename,'*.CSV'):
            print (filename)

Lab:Gainsville
admin_2019-05-28 17-00-41_CT016386.csv
admin_2019-05-29 21-09-48_CT016386.csv
admin_2019-05-30 16-35-36_CT016386_L. mono..csv
admin_2019-05-30 19-09-41_CT016386_L. mono..csv
admin_2019-05-30 21-29-21_CT016386_L. mono..csv
admin_2019-05-31 15-20-04_CT016386_L. mono..csv
admin_2019-05-31 20-07-35_CT016386_L. mono..csv
admin_2019-06-01 16-22-14_CT016386_L. mono..csv
admin_2019-06-01 20-03-05_CT016386_L. mono..csv
admin_2019-06-02 17-28-26_CT016386_L. mono..csv

In [53]:
path= './/SampleFiles_Instruments//BioRad//'
filename='admin_2019-05-30 16-35-36_CT016386_L. mono..csv'
datapath = path + str(filename)
rawdf = pd.read_csv(datapath,sep=',',index_col=False,skiprows=23)

In [54]:
rawdf

,Well,Fluor,Target,Content,Replicate,Sample,Biological Set Name,Well Note,Cq,Starting Quantity (SQ),Cq Mean,Cq Std. Dev,SQ Std. Dev,Melt Temperature,Peak Height,Begin Temperature,End Temperature,Call,End RFU,Result
0,A01,FAM,NaN,Unkn,NaN,388636647.0,NaN,NaN,NaN,NaN,0.000000,0,0,NaN,NaN,NaN,NaN,NaN,-31.429438,Negative
1,A02,FAM,NaN,Unkn,NaN,388637254.0,NaN,NaN,NaN,NaN,0.000000,0,0,NaN,NaN,NaN,NaN,NaN,-309.770103,Negative
2,B01,FAM,NaN,Unkn,NaN,388636677.0,NaN,NaN,NaN,NaN,0.000000,0,0,NaN,NaN,NaN,NaN,NaN,-50.750056,Negative
3,B02,FAM,NaN,Unkn,NaN,388637346.0,NaN,NaN,NaN,NaN,0.000000,0,0,NaN,NaN,NaN,NaN,NaN,-45.592750,Negative
4,C01,FAM,NaN,Unkn,NaN,388636754.0,NaN,NaN,NaN,NaN,0.000000,0,0,NaN,NaN,NaN,NaN,NaN,-167.223127,Negative
5,C02,FAM,NaN,Unkn,NaN,388637364.0,NaN,NaN,NaN,NaN,0.000000,0,0,NaN,NaN,NaN,NaN,NaN,-173.314916,Negative
6,D01,FAM,NaN,Unkn,NaN,388636976.0,NaN,NaN,NaN,NaN,0.000000,0,0,NaN,NaN,NaN,NaN,NaN,-92.998778,Negative
7,D02,FAM,NaN,Unkn,NaN,388640562.0,NaN,NaN,NaN,NaN,0.000000,0,0,NaN,NaN,NaN,NaN,NaN,-266.115857,Negative
8,E01,FAM,NaN,Unkn,NaN,388637092.0,NaN,NaN,NaN,NaN,0.000000,0,0,NaN,NaN,NaN,NaN,NaN,-215.051414,Negative
9,E02,FAM,NaN,Unkn,NaN,388640596.0,NaN,NaN,25.771888,NaN,25.771888,0,0,NaN,NaN,NaN,NaN,(+) Positive,11590.654082,Positive
10,F01,FAM,NaN,Unkn,NaN,388637127.0,NaN,NaN,NaN,NaN,0.000000,0,0,NaN,NaN,NaN,NaN,NaN,-213.296165,Negative
11,G01,FAM,NaN,Unkn,NaN,388637159.0,NaN,NaN,NaN,NaN,0.000000,0,0,NaN,NaN,NaN,NaN,NaN,-307.664306,Negative
12,G02,FAM,NaN,Neg Ctrl,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0,0,NaN,NaN,NaN,NaN,NaN,9.007285,Valid Ctrl
13,H01,FAM,NaN,Unkn,NaN,388637220.0,NaN,NaN,NaN,NaN,0.000000,0,0,NaN,NaN,NaN,NaN,NaN,-72.431937,Negative
14,H02,FAM,NaN,Pos Ctrl,NaN,NaN,NaN,NaN,29.937481,NaN,29.937481,0,0,NaN,NaN,NaN,NaN,(+) Positive,10665.077771,Valid Ctrl
15,A01,HEX,NaN,Unkn,NaN,388636647.0,NaN,NaN,36.691861,NaN,36.691861,0,0,NaN,NaN,NaN,NaN,NaN,4344.208560,Negative
16,A02,HEX,NaN,Unkn,NaN,388637254.0,NaN,NaN,34.626132,NaN,34.626132,0,0,NaN,NaN,NaN,NaN,NaN,6469.946093,Negative
17,B01,HEX,NaN,Unkn,NaN,388636677.0,NaN,NaN,35.194745,NaN,35.194745,0,0,NaN,NaN,NaN,NaN,NaN,5081.666522,Negative
18,B02,HEX,NaN,Unkn,NaN,388637346.0,NaN,NaN,33.804907,NaN,33.804907,0,0,NaN,NaN,NaN,NaN,NaN,3784.907662,Negative
19,C01,HEX,NaN,Unkn,NaN,388636754.0,NaN,NaN,35.355442,NaN,35.355442,0,0,NaN,NaN,NaN,NaN,NaN,5947.466544,Negative
20,C02,HEX,NaN,Unkn,NaN,388637364.0,NaN,NaN,34.139391,NaN,34.139391,0,0,NaN,NaN,NaN,NaN,NaN,6758.521350,Negative
21,D01,HEX,NaN,Unkn,NaN,388636976.0,NaN,NaN,35.743815,NaN,35.743815,0,0,NaN,NaN,NaN,NaN,NaN,5024.691492,Negative
22,D02,HEX,NaN,Unkn,NaN,388640562.0,NaN,NaN,33.547564,NaN,33.547564,0,0,NaN,NaN,NaN,NaN,NaN,6496.710315,Negative
23,E01,HEX,NaN,Unkn,NaN,388637092.0,NaN,NaN,35.122500,NaN,35.122500,0,0,NaN,NaN,NaN,NaN,NaN,6172.860107,Negative
24,E02,HEX,NaN,Unkn,NaN,388640596.0,NaN,NaN,32.501781,NaN,32.501781,0,0,NaN,NaN,NaN,NaN,NaN,5384.946328,Positive
25,F01,HEX,NaN,Unkn,NaN,388637127.0,NaN,NaN,33.936767,NaN,33.936767,0,0,NaN,NaN,NaN,NaN,NaN,6345.503814,Negative
26,G01,HEX,NaN,Unkn,NaN,388637159.0,NaN,NaN,33.883475,NaN,33.883475,0,0,NaN,NaN,NaN,NaN,(+) Positive,6939.547413,Negative
27,G02,HEX,NaN,Neg Ctrl,NaN,NaN,NaN,NaN,33.083856,NaN,33.083856,0,0,NaN,NaN,NaN,NaN,NaN,6750.644029,Valid Ctrl
28,H01,HEX,NaN,Unkn,NaN,388637220.0,NaN,NaN,33.471566,NaN,33.471566,0,0,NaN,NaN,NaN,NaN,NaN,4924.510078,Negative
29,H02,HEX,NaN,Pos Ctrl,NaN,NaN,NaN,NaN,33.414436,NaN,33.414436,0,0,NaN,NaN,NaN,NaN,NaN,5274.614744,Valid Ctrl

In [55]:
rawdf=rawdf.rename(index=str,columns={'Sample': 'sample_number'})
rawdf = rawdf[pd.notnull(rawdf['sample_number'])]
rawdf=rawdf.astype({"sample_number": int})
rawdf=rawdf.astype({"sample_number": str})

In [57]:
sampleNumbersList=list(rawdf['sample_number'].unique())
databasedf=getDataFromDB(sampleNumbersList)
rawdf=rawdf.astype({"sample_number": int})
dfResult = rawdf.merge(databasedf, how = 'inner', on = ['sample_number'])

In [58]:
dfResult=dfResult.rename(index=str, 
columns={'sample_number': 'Sample.Sample_Number', 'Result': 'Result.Entry','Titrant volume for sample (ml)': 'Result.Entry','test_number':'Test.Test_Number'})

In [60]:
dfResultReplicateMax = dfResult.groupby('Sample.Sample_Number')['replicate_count'].max().reset_index()
dfResultFinal = dfResult.merge(dfResultReplicateMax, how = 'inner', on = ['Sample.Sample_Number','replicate_count'])

In [61]:
dfResultFinal['Result.Name']='PCR'
dfResultFinal['Result.Entered_By']='IMPORTER'
dfResultFinal['Result.Instrument']='BIO-RAD'
dfResultFinal = dfResultFinal[colsOrder]

In [62]:
dfResultFinal

,Sample.Sample_Number,Test.Test_Number,Result.Name,Result.Entry,Result.Entered_By,Result.Instrument
0,388636647,649072651,PCR,Negative,IMPORTER,BIO-RAD
1,388636647,649072651,PCR,Negative,IMPORTER,BIO-RAD
2,388637254,649084948,PCR,Negative,IMPORTER,BIO-RAD
3,388637254,649084948,PCR,Negative,IMPORTER,BIO-RAD
4,388636677,649072656,PCR,Negative,IMPORTER,BIO-RAD
5,388636677,649072656,PCR,Negative,IMPORTER,BIO-RAD
6,388637346,649085459,PCR,Negative,IMPORTER,BIO-RAD
7,388637346,649085459,PCR,Negative,IMPORTER,BIO-RAD
8,388636754,649072660,PCR,Negative,IMPORTER,BIO-RAD
9,388636754,649072660,PCR,Negative,IMPORTER,BIO-RAD
10,388637364,649085463,PCR,Negative,IMPORTER,BIO-RAD
11,388637364,649085463,PCR,Negative,IMPORTER,BIO-RAD
12,388636976,649072665,PCR,Negative,IMPORTER,BIO-RAD
13,388636976,649072665,PCR,Negative,IMPORTER,BIO-RAD
14,388640562,649091385,PCR,Negative,IMPORTER,BIO-RAD
15,388640562,649091385,PCR,Negative,IMPORTER,BIO-RAD
16,388637092,649072669,PCR,Negative,IMPORTER,BIO-RAD
17,388637092,649072669,PCR,Negative,IMPORTER,BIO-RAD
18,388640596,649091940,PCR,Positive,IMPORTER,BIO-RAD
19,388640596,649091940,PCR,Positive,IMPORTER,BIO-RAD
20,388637127,649084934,PCR,Negative,IMPORTER,BIO-RAD
21,388637127,649084934,PCR,Negative,IMPORTER,BIO-RAD
22,388637159,649084938,PCR,Negative,IMPORTER,BIO-RAD
23,388637159,649084938,PCR,Negative,IMPORTER,BIO-RAD
24,388637220,649084943,PCR,Negative,IMPORTER,BIO-RAD
25,388637220,649084943,PCR,Negative,IMPORTER,BIO-RAD

In [ ]:
writeFile(dfResultFinal,lab,inst,path,importDest,datapath,fname)