In [61]:
# Import Functions
import pandas as pd
import os
import time
import csv
import json
import fnmatch
import csv
import sqlalchemy as sql
import numpy as np
dbHost='mxnunx41'
dbPort='1521'
dbUser='lims'
dbPassword='Mumwit63'
dbName='hwi1'
dburl='oracle://'

In [62]:
# Default Parameters setting
with open('.\configFiles\DumathermConfig.json', 'r') as f:
    config = json.load(f)
lab = config['lab']
analysis = config['analysis']
inst = config['inst']
colsOrder=['Sample.Sample_Number', 'Test.Test_Number','Result.Name', 'Result.Entry', 'Result.Entered_By','Result.Instrument']

In [63]:
# get Data from DB
def getDataFromDB(sampleNumbersList):
    dburl = 'oracle://'+dbUser+':'+dbPassword+'@'+dbHost+':'+dbPort+'/'+dbName
    engine=sql.create_engine(dburl)
    resultdf=pd.DataFrame()
    sampleNumbrStr=(', '.join("'" + str(item) + "'" for item in sampleNumbersList))
    queryText="SELECT sample_number, analysis, REPLICATE_COUNT,TEST_NUMBER FROM test"
    queryText=queryText+" WHERE SAMPLE_NUMBER IN ("+sampleNumbrStr+") AND analysis IN ('PROT-COMII', 'PROT-HICOM')"
    conn = engine.connect()
    resultdf = pd.read_sql(queryText, engine)
    conn.close()
    return resultdf

In [64]:
#write the file
def writeFile(dframe,lab,inst,archDestination,importDest,datapath,fname):
    timestr = time.strftime("%Y%m%d%H%M%S")
    FileName = importDest + lab+'_'+inst+'_' + timestr + '.csv'
    dframe.to_csv(FileName, index=False, encoding="utf-8",quotechar='"',quoting=csv.QUOTE_NONNUMERIC) # write  out the file to be imported
    destination = archDestination + fname[:-4] + '.bak' # Backup the processed file
    os.rename(datapath, destination)
    time.sleep(1)

In [65]:
for eachlab in lab:
    path='//mxns.loc//shares//NA-Instruments//Prod//'+eachlab+'//Import//'+inst+'//'
    archivedDestination='//mxns.loc//shares//NA-Instruments//Prod//'+eachlab+'//Import//'+inst+'//'
    importDest='//mxns.loc//shares//NA-Instruments//Prod//'+eachlab+'//impf//'
    print(path)
    if os.path.exists(path):
        break
    else:
        os.makedirs(path)
    files = os.listdir(path)
    for filename in files:
        if fnmatch.fnmatch(filename,'*.CSV'):
            print (filename)

//mxns.loc//shares//NA-Instruments//Prod//Crete//Import//Dumatherm//

In [66]:
filename='Export_812_2019_03_18_09_25.csv'
datapath = path + str(filename)
rawdf = pd.read_csv(datapath,header=None)

In [67]:
rawdf = rawdf.rename(index=str, columns={0: 'sample_number', 1: 'var1', 2: 'var2'})

In [68]:
sampleNumbersList=list(rawdf['sample_number'].unique())
databasedf=getDataFromDB(sampleNumbersList)
rawdf=rawdf.astype({"sample_number": int})
dfResult = rawdf.merge(databasedf, how = 'inner', on = ['sample_number'])

In [69]:
dfResult

    sample_number   var1  var2    analysis  replicate_count  test_number
0       386356569  104.8  9.61  PROT-COMII                1    644031964
1       386356574  103.6  9.59  PROT-COMII                1    644031965
2       386356575  257.1  3.21  PROT-COMII                1    644031966
3       386260010  216.4  2.17  PROT-COMII                1    643824693
4       386260016  156.6  2.09  PROT-COMII                1    643824694
5       386260021  181.0  2.30  PROT-COMII                1    643824695
6       386260026  169.0  2.40  PROT-COMII                1    643824696
7       386260323  195.7  2.31  PROT-COMII                1    643825789
8       386260324  205.7  2.33  PROT-COMII                1    643825790
9       386260327  183.2  2.10  PROT-COMII                1    643825791
10      386260329  181.5  2.34  PROT-COMII                1    643825792
11      386289541  192.4  0.66  PROT-COMII                1    643897382
12      386289569  190.4  0.11  PROT-COMII                1    643899058
13      386289601  210.2  0.62  PROT-COMII                1    643899176
14      386289716  171.2  1.63  PROT-COMII                1    643899191
15      386289809  196.0  0.66  PROT-COMII                1    643899206
16      386356605  102.0  9.57  PROT-COMII                1    644031967
17      386297131  174.3  5.79  PROT-COMII                1    643910529
18      386308941  133.4  2.06  PROT-COMII                1    643939927
19      386308941  133.4  2.06  PROT-COMII                2    644090975
20      386326558  268.0  2.37  PROT-COMII                1    643978534
21      386326714  174.8  0.21  PROT-COMII                1    643978550
22      386326814  194.2  0.05  PROT-COMII                1    643979648
23      386327018  200.7  0.31  PROT-COMII                1    643980101
24      386327030  231.1  0.11  PROT-COMII                1    643979664
25      386356614  253.5  3.22  PROT-COMII                1    644032288
26      386356625  102.3  9.53  PROT-COMII                1    644032289

In [70]:
dfResult=dfResult.rename(index=str, 
columns={'sample_number': 'Sample.Sample_Number', 'var2': 'Result.Entry','test_number':'Test.Test_Number'})

In [71]:
dfResult

,Sample.Sample_Number,var1,Result.Entry,analysis,replicate_count,Test.Test_Number
0,386356569,104.8,9.61,PROT-COMII,1,644031964
1,386356574,103.6,9.59,PROT-COMII,1,644031965
2,386356575,257.1,3.21,PROT-COMII,1,644031966
3,386260010,216.4,2.17,PROT-COMII,1,643824693
4,386260016,156.6,2.09,PROT-COMII,1,643824694
5,386260021,181.0,2.30,PROT-COMII,1,643824695
6,386260026,169.0,2.40,PROT-COMII,1,643824696
7,386260323,195.7,2.31,PROT-COMII,1,643825789
8,386260324,205.7,2.33,PROT-COMII,1,643825790
9,386260327,183.2,2.10,PROT-COMII,1,643825791
10,386260329,181.5,2.34,PROT-COMII,1,643825792
11,386289541,192.4,0.66,PROT-COMII,1,643897382
12,386289569,190.4,0.11,PROT-COMII,1,643899058
13,386289601,210.2,0.62,PROT-COMII,1,643899176
14,386289716,171.2,1.63,PROT-COMII,1,643899191
15,386289809,196.0,0.66,PROT-COMII,1,643899206
16,386356605,102.0,9.57,PROT-COMII,1,644031967
17,386297131,174.3,5.79,PROT-COMII,1,643910529
18,386308941,133.4,2.06,PROT-COMII,1,643939927
19,386308941,133.4,2.06,PROT-COMII,2,644090975
20,386326558,268.0,2.37,PROT-COMII,1,643978534
21,386326714,174.8,0.21,PROT-COMII,1,643978550
22,386326814,194.2,0.05,PROT-COMII,1,643979648
23,386327018,200.7,0.31,PROT-COMII,1,643980101
24,386327030,231.1,0.11,PROT-COMII,1,643979664
25,386356614,253.5,3.22,PROT-COMII,1,644032288
26,386356625,102.3,9.53,PROT-COMII,1,644032289

In [72]:
dfResultReplicateMax = dfResult.groupby('Sample.Sample_Number')['replicate_count'].max().reset_index()
dfResultFinal = dfResult.merge(dfResultReplicateMax, how = 'inner', on = ['Sample.Sample_Number','replicate_count'])

In [73]:
dfResultFinal

,Sample.Sample_Number,var1,Result.Entry,analysis,replicate_count,Test.Test_Number
0,386356569,104.8,9.61,PROT-COMII,1,644031964
1,386356574,103.6,9.59,PROT-COMII,1,644031965
2,386356575,257.1,3.21,PROT-COMII,1,644031966
3,386260010,216.4,2.17,PROT-COMII,1,643824693
4,386260016,156.6,2.09,PROT-COMII,1,643824694
5,386260021,181.0,2.30,PROT-COMII,1,643824695
6,386260026,169.0,2.40,PROT-COMII,1,643824696
7,386260323,195.7,2.31,PROT-COMII,1,643825789
8,386260324,205.7,2.33,PROT-COMII,1,643825790
9,386260327,183.2,2.10,PROT-COMII,1,643825791
10,386260329,181.5,2.34,PROT-COMII,1,643825792
11,386289541,192.4,0.66,PROT-COMII,1,643897382
12,386289569,190.4,0.11,PROT-COMII,1,643899058
13,386289601,210.2,0.62,PROT-COMII,1,643899176
14,386289716,171.2,1.63,PROT-COMII,1,643899191
15,386289809,196.0,0.66,PROT-COMII,1,643899206
16,386356605,102.0,9.57,PROT-COMII,1,644031967
17,386297131,174.3,5.79,PROT-COMII,1,643910529
18,386308941,133.4,2.06,PROT-COMII,2,644090975
19,386326558,268.0,2.37,PROT-COMII,1,643978534
20,386326714,174.8,0.21,PROT-COMII,1,643978550
21,386326814,194.2,0.05,PROT-COMII,1,643979648
22,386327018,200.7,0.31,PROT-COMII,1,643980101
23,386327030,231.1,0.11,PROT-COMII,1,643979664
24,386356614,253.5,3.22,PROT-COMII,1,644032288
25,386356625,102.3,9.53,PROT-COMII,1,644032289

In [74]:
dfResultFinal['Result.Name']='Nitrogen (from instrument)'
dfResultFinal['Result.Entered_By']='IMPORTER'
dfResultFinal['Result.Instrument']='Dumatherm'

In [75]:
dfResultFinal

,Sample.Sample_Number,var1,Result.Entry,analysis,replicate_count,Test.Test_Number,Result.Name,Result.Entered_By,Result.Instrument
0,386356569,104.8,9.61,PROT-COMII,1,644031964,Nitrogen (from instrument),IMPORTER,Dumatherm
1,386356574,103.6,9.59,PROT-COMII,1,644031965,Nitrogen (from instrument),IMPORTER,Dumatherm
2,386356575,257.1,3.21,PROT-COMII,1,644031966,Nitrogen (from instrument),IMPORTER,Dumatherm
3,386260010,216.4,2.17,PROT-COMII,1,643824693,Nitrogen (from instrument),IMPORTER,Dumatherm
4,386260016,156.6,2.09,PROT-COMII,1,643824694,Nitrogen (from instrument),IMPORTER,Dumatherm
5,386260021,181.0,2.30,PROT-COMII,1,643824695,Nitrogen (from instrument),IMPORTER,Dumatherm
6,386260026,169.0,2.40,PROT-COMII,1,643824696,Nitrogen (from instrument),IMPORTER,Dumatherm
7,386260323,195.7,2.31,PROT-COMII,1,643825789,Nitrogen (from instrument),IMPORTER,Dumatherm
8,386260324,205.7,2.33,PROT-COMII,1,643825790,Nitrogen (from instrument),IMPORTER,Dumatherm
9,386260327,183.2,2.10,PROT-COMII,1,643825791,Nitrogen (from instrument),IMPORTER,Dumatherm
10,386260329,181.5,2.34,PROT-COMII,1,643825792,Nitrogen (from instrument),IMPORTER,Dumatherm
11,386289541,192.4,0.66,PROT-COMII,1,643897382,Nitrogen (from instrument),IMPORTER,Dumatherm
12,386289569,190.4,0.11,PROT-COMII,1,643899058,Nitrogen (from instrument),IMPORTER,Dumatherm
13,386289601,210.2,0.62,PROT-COMII,1,643899176,Nitrogen (from instrument),IMPORTER,Dumatherm
14,386289716,171.2,1.63,PROT-COMII,1,643899191,Nitrogen (from instrument),IMPORTER,Dumatherm
15,386289809,196.0,0.66,PROT-COMII,1,643899206,Nitrogen (from instrument),IMPORTER,Dumatherm
16,386356605,102.0,9.57,PROT-COMII,1,644031967,Nitrogen (from instrument),IMPORTER,Dumatherm
17,386297131,174.3,5.79,PROT-COMII,1,643910529,Nitrogen (from instrument),IMPORTER,Dumatherm
18,386308941,133.4,2.06,PROT-COMII,2,644090975,Nitrogen (from instrument),IMPORTER,Dumatherm
19,386326558,268.0,2.37,PROT-COMII,1,643978534,Nitrogen (from instrument),IMPORTER,Dumatherm
20,386326714,174.8,0.21,PROT-COMII,1,643978550,Nitrogen (from instrument),IMPORTER,Dumatherm
21,386326814,194.2,0.05,PROT-COMII,1,643979648,Nitrogen (from instrument),IMPORTER,Dumatherm
22,386327018,200.7,0.31,PROT-COMII,1,643980101,Nitrogen (from instrument),IMPORTER,Dumatherm
23,386327030,231.1,0.11,PROT-COMII,1,643979664,Nitrogen (from instrument),IMPORTER,Dumatherm
24,386356614,253.5,3.22,PROT-COMII,1,644032288,Nitrogen (from instrument),IMPORTER,Dumatherm
25,386356625,102.3,9.53,PROT-COMII,1,644032289,Nitrogen (from instrument),IMPORTER,Dumatherm

In [76]:
dfResultFinal = dfResultFinal[colsOrder]

In [77]:
dfResultFinal

,Sample.Sample_Number,Test.Test_Number,Result.Name,Result.Entry,Result.Entered_By,Result.Instrument
0,386356569,644031964,Nitrogen (from instrument),9.61,IMPORTER,Dumatherm
1,386356574,644031965,Nitrogen (from instrument),9.59,IMPORTER,Dumatherm
2,386356575,644031966,Nitrogen (from instrument),3.21,IMPORTER,Dumatherm
3,386260010,643824693,Nitrogen (from instrument),2.17,IMPORTER,Dumatherm
4,386260016,643824694,Nitrogen (from instrument),2.09,IMPORTER,Dumatherm
5,386260021,643824695,Nitrogen (from instrument),2.30,IMPORTER,Dumatherm
6,386260026,643824696,Nitrogen (from instrument),2.40,IMPORTER,Dumatherm
7,386260323,643825789,Nitrogen (from instrument),2.31,IMPORTER,Dumatherm
8,386260324,643825790,Nitrogen (from instrument),2.33,IMPORTER,Dumatherm
9,386260327,643825791,Nitrogen (from instrument),2.10,IMPORTER,Dumatherm
10,386260329,643825792,Nitrogen (from instrument),2.34,IMPORTER,Dumatherm
11,386289541,643897382,Nitrogen (from instrument),0.66,IMPORTER,Dumatherm
12,386289569,643899058,Nitrogen (from instrument),0.11,IMPORTER,Dumatherm
13,386289601,643899176,Nitrogen (from instrument),0.62,IMPORTER,Dumatherm
14,386289716,643899191,Nitrogen (from instrument),1.63,IMPORTER,Dumatherm
15,386289809,643899206,Nitrogen (from instrument),0.66,IMPORTER,Dumatherm
16,386356605,644031967,Nitrogen (from instrument),9.57,IMPORTER,Dumatherm
17,386297131,643910529,Nitrogen (from instrument),5.79,IMPORTER,Dumatherm
18,386308941,644090975,Nitrogen (from instrument),2.06,IMPORTER,Dumatherm
19,386326558,643978534,Nitrogen (from instrument),2.37,IMPORTER,Dumatherm
20,386326714,643978550,Nitrogen (from instrument),0.21,IMPORTER,Dumatherm
21,386326814,643979648,Nitrogen (from instrument),0.05,IMPORTER,Dumatherm
22,386327018,643980101,Nitrogen (from instrument),0.31,IMPORTER,Dumatherm
23,386327030,643979664,Nitrogen (from instrument),0.11,IMPORTER,Dumatherm
24,386356614,644032288,Nitrogen (from instrument),3.22,IMPORTER,Dumatherm
25,386356625,644032289,Nitrogen (from instrument),9.53,IMPORTER,Dumatherm

In [78]:
writeFile(dfResultFinal,eachlab,inst,path,importDest,datapath,filename)