In [44]:
import pandas as pd
import numpy as np
import os, fnmatch

In [45]:
listOfFiles = os.listdir('.')  
csvpattern = "*.csv"  
xlxspattern = "*.xlsx"
limsFname=''
JDEFname=''
for entry in listOfFiles: 
    if fnmatch.fnmatch(entry, csvpattern):
        limsFname=entry
    if fnmatch.fnmatch(entry, xlxspattern):
        JDEFname=entry

In [46]:
JDEFname

'133347_JDE.xlsx'

In [47]:
dflims = pd.read_csv(limsFname)

In [48]:
dflims

,PRICING RULE DEFINITION,Pricing Rule :,Disc,Price,Auto Analysis Up :,T,Changed By :,HE-CY,Auto Analysis Down :,T.1,...,1/25/2018,Item,Discount %,Price.1,Analysis : ICP-DRY,0,27.1,12/13/2018 9:45:30AM,Unnamed: 19,Page 1 of 1
0,PRICING RULE DEFINITION,Analysis : MOIST-FAO,0,20.14,12/13/2018 9:45:30AM,NaN,Page 1 of 1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,PRICING RULE DEFINITION,Analysis : PH,0,12.20,12/13/2018 9:45:30AM,NaN,Page 1 of 1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,PRICING RULE DEFINITION,Analysis : PHOSPH-ICP,0,14.82,12/13/2018 9:45:30AM,NaN,Page 1 of 1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,PRICING RULE DEFINITION,Analysis : SODIUM-ICP,0,14.25,12/13/2018 9:45:30AM,NaN,Page 1 of 1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,PRICING RULE DEFINITION,Category : Biotechnology,40,0.00,12/13/2018 9:45:30AM,NaN,Page 1 of 1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,PRICING RULE DEFINITION,Category : Dairy,40,0.00,12/13/2018 9:45:30AM,NaN,Page 1 of 1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,PRICING RULE DEFINITION,Category : Extraneous Matter,40,0.00,12/13/2018 9:45:30AM,NaN,Page 1 of 1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,PRICING RULE DEFINITION,Category : Instrumental Chemistry,40,0.00,12/13/2018 9:45:30AM,NaN,Page 1 of 1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,PRICING RULE DEFINITION,Category : IRMA,40,0.00,12/13/2018 9:45:30AM,NaN,Page 1 of 1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,PRICING RULE DEFINITION,Category : Physical Testing,40,0.00,12/13/2018 9:45:30AM,NaN,Page 1 of 1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,PRICING RULE DEFINITION,Category : Qualitative Micro,40,0.00,12/13/2018 9:45:30AM,NaN,Page 1 of 1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,PRICING RULE DEFINITION,Category : Quantitative Micro,40,0.00,12/13/2018 9:45:30AM,NaN,Page 1 of 1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,PRICING RULE DEFINITION,Category : Vitamins,40,0.00,12/13/2018 9:45:30AM,NaN,Page 1 of 1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,PRICING RULE DEFINITION,Category : Wet Chemistry,40,0.00,12/13/2018 9:45:30AM,NaN,Page 1 of 1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
dflims['type'], dflims['testCodeL'] = dflims['Pricing Rule : '].str.split(':', 1).str

In [50]:
dflims.columns

Index(['PRICING RULE DEFINITION', 'Pricing Rule : ', 'Disc', 'Price',
       'Auto Analysis Up :', 'T', 'Changed By :', 'HE-CY',
       'Auto Analysis Down :', 'T.1', 'Changed On :', '1/25/2018', 'Item',
       'Discount %', 'Price.1', 'Analysis : ICP-DRY', '0', '27.1',
       '12/13/2018  9:45:30AM', 'Unnamed: 19', 'Page 1 of 1', 'type',
       'testCodeL'],
      dtype='object')

In [51]:
col_list_lims = ['type', 'testCodeL','Disc','Price']

In [52]:
dflims1 = dflims[col_list_lims]

In [53]:
dflims2 = dflims1.loc[dflims1['type'] == 'Analysis ']

In [54]:
dflims2

        type    testCodeL  Disc  Price
0  Analysis     MOIST-FAO     0  20.14
1  Analysis            PH     0  12.20
2  Analysis    PHOSPH-ICP     0  14.82
3  Analysis    SODIUM-ICP     0  14.25

In [31]:
dflims2['testCodeL']=dflims2['testCodeL'].str.strip()
dflims2=dflims2.round(2)

c:\users\agundlapalli\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [32]:
dflims2

        type   testCodeL  Disc  Price
0  Analysis    MOIST-FAO     0    NaN
1  Analysis           PH     0    NaN
2  Analysis   PHOSPH-ICP     0    NaN
3  Analysis   SODIUM-ICP     0    NaN

In [12]:
#JDE
dfjde = pd.read_excel(JDEFname)

In [13]:
dfjde

,Address Number,Factor Value Numeric,Item Grp 01,Item Grp 1 Description,2nd Item Number,Customer Group,Cur Cod,Effective Date,Expired Date,Adj Name,...,Cust Grp 3,Cust Grp 4,Cust Grp 5,Cust Grp 6,Cust Grp 7,Cust Grp 8,Cust Grp 9,Cust Grp 10,Short Item No,3rd Item Number
0,133347,20.1365,17,MOIST-FAO,,,USD,2018-02-01,2018-12-31,CONTRACT,...,,,,,,,,,0,
1,133347,28.1840,172,ICP-DRY,,,USD,2018-02-01,2018-12-31,CONTRACT,...,,,,,,,,,0,
2,133347,12.6880,8,PH,,,USD,2018-02-01,2018-12-31,CONTRACT,...,,,,,,,,,0,
3,133347,15.4128,409,PHOSPH-ICP,,,USD,2018-02-01,2018-12-31,CONTRACT,...,,,,,,,,,0,
4,133347,14.8200,395,SODIUM-ICP,,,USD,2018-02-01,2018-12-31,CONTRACT,...,,,,,,,,,0,

In [14]:
col_list_jde=['Item Grp 1 Description','Factor Value Numeric']

In [15]:
dfjde1 = dfjde[col_list_jde]
dfjde1.rename(columns={'Item Grp 1 Description': 'testCodeJ', 'Factor Value Numeric': 'PriceJDE'}, inplace=True)

c:\users\agundlapalli\appdata\local\programs\python\python36\lib\site-packages\pandas\core\frame.py:3781: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

In [16]:
dfjde1

    testCodeJ  PriceJDE
0   MOIST-FAO   20.1365
1     ICP-DRY   28.1840
2          PH   12.6880
3  PHOSPH-ICP   15.4128
4  SODIUM-ICP   14.8200

In [17]:
dfjde1=dfjde1.sort_values(by=['testCodeJ'])

In [18]:
dfjde1 = dfjde1.reset_index(drop=True)

In [19]:
dfjde1['PriceJDE'].fillna(0, inplace=True)

In [20]:
dfjde1

    testCodeJ  PriceJDE
0     ICP-DRY   28.1840
1   MOIST-FAO   20.1365
2          PH   12.6880
3  PHOSPH-ICP   15.4128
4  SODIUM-ICP   14.8200

In [21]:
dflims2.head()

        type   testCodeL  Disc  Price
0  Analysis    MOIST-FAO     0    NaN
1  Analysis           PH     0    NaN
2  Analysis   PHOSPH-ICP     0    NaN
3  Analysis   SODIUM-ICP     0    NaN

In [163]:
dfjde1['testCodeJ']=dfjde1['testCodeJ'].str.strip()
dfjde1=dfjde1.round(2)

In [164]:
dfResult = dflims2.merge(dfjde1, left_on='testCodeL', right_on='testCodeJ', how='outer')

In [165]:
dfjde1

      testCodeJ  PriceJDE
0    ACID-TITRA     16.90
1    ACID-VALUE     54.32
2    AFLA-LC-BG     59.67
3    AFLAT-HPLC     59.67
4    AFLATX-VIC     34.81
5    ALLERG-MLK     55.00
6    ALLERGPNUT     55.00
7    AMINO-CMPL    288.64
8    AMINO-SCOR     89.50
9    AMINOGLYCO    311.00
10        ANAPC     17.55
11   ANTIMON-MS     30.33
12          APC      5.22
13    APC-AIR-C      3.23
14   APC-HETERO      9.95
15    APC-PETRI      5.22
16   ARSENIC-MS     26.66
17          ASH     15.11
18    BARIUM-MS     29.17
19   BCEREUSPRE     12.43
20   BHA-T-TBHQ    249.51
21         BRIX     13.43
22   CADMIUM-MS     26.66
23     CAFFEINE    130.44
24   CALCIU-ICP     10.63
25   CHLORIN-TR     33.81
26     CHLORINE     28.79
27   CHOLESTERO    100.58
28   CHROMIU-MS     29.17
29    COLI-HGMF      8.93
..          ...       ...
164  SODIUM-ICP     10.63
165  SOLID-DSLV     32.18
166   SOLID-FAO     14.63
167    SOLID-VO     14.63
168     SORBATE    115.05
169   STAPH-CPS      6.46
170  STAPH-ELFA    125.00
171  STAPH-XPRS      6.46
172  STARCH-ENZ    126.36
173  SUGR-DP1-2     92.59
174     SULFITE    106.51
175   THERMOAER     27.85
176      TIN-MS     26.66
177  VISC-BROOK     41.46
178    VIT-B1-C     74.10
179   VIT-B12-C    112.13
180    VIT-B2-C     90.43
181    VIT-B3-C     77.80
182     VIT-C-C    116.84
183   VIT-D2-D3    258.38
184   VITAMIN-A    108.66
185  VITAMIN-D3    180.77
186   VITAMIN-E    145.98
187   WATER-ACT     36.80
188       YEAST      2.61
189          YM      5.22
190  YM-2DPETRI      9.01
191    YM-AIR-C      5.22
192     YM-OSMO     12.92
193    YM-PETRI      5.22

[194 rows x 2 columns]

In [166]:
dfResult

          type   testCodeL  Disc   Price   testCodeJ  PriceJDE
0    Analysis   ACID-VALUE   0.0   54.32  ACID-VALUE     54.32
1    Analysis   AFLA-LC-BG   0.0   59.67  AFLA-LC-BG     59.67
2    Analysis   AFLAT-HPLC   0.0   59.67  AFLAT-HPLC     59.67
3    Analysis   AFLATX-VIC   0.0   34.81  AFLATX-VIC     34.81
4    Analysis   ALLERG-MLK   0.0   55.00  ALLERG-MLK     55.00
5    Analysis   ALLERGPNUT   0.0   55.00  ALLERGPNUT     55.00
6    Analysis   AMINO-CMPL   0.0  288.64  AMINO-CMPL    288.64
7    Analysis   AMINOGLYCO   0.0  311.00  AMINOGLYCO    311.00
8    Analysis   AMINO-SCOR   0.0   89.50  AMINO-SCOR     89.50
9    Analysis        ANAPC   0.0   17.55       ANAPC     17.55
10   Analysis   ANTIMON-MS   0.0   30.33  ANTIMON-MS     30.33
11   Analysis          APC   0.0    5.22         APC      5.22
12   Analysis    APC-AIR-C   0.0    3.23   APC-AIR-C      3.23
13   Analysis   APC-HETERO   0.0    9.95  APC-HETERO      9.95
14   Analysis    APC-PETRI   0.0    5.22   APC-PETRI      5.22
15   Analysis   ARSENIC-MS   0.0   26.66  ARSENIC-MS     26.66
16   Analysis          ASH   0.0   15.11         ASH     15.11
17   Analysis    BARIUM-MS   0.0   29.17   BARIUM-MS     29.17
18   Analysis   BCEREUSPRE   0.0   12.43  BCEREUSPRE     12.43
19   Analysis   BHA-T-TBHQ   0.0  249.51  BHA-T-TBHQ    249.51
20   Analysis         BRIX   0.0   13.43        BRIX     13.43
21   Analysis   CADMIUM-MS   0.0   26.66  CADMIUM-MS     26.66
22   Analysis     CAFFEINE   0.0  130.44    CAFFEINE    130.44
23   Analysis   CALCIU-ICP   0.0   10.63  CALCIU-ICP     10.63
24   Analysis     CHLORINE   0.0   28.79    CHLORINE     28.79
25   Analysis   CHLORIN-TR   0.0   33.81  CHLORIN-TR     33.81
26   Analysis   CHOLESTERO   0.0  100.58  CHOLESTERO    100.58
27   Analysis   CHROMIU-MS   0.0   29.17  CHROMIU-MS     29.17
28   Analysis    COLI-HGMF   0.0    8.93   COLI-HGMF      8.93
29   Analysis   COLILERTPA   0.0   25.99  COLILERTPA     25.99
..         ...         ...   ...     ...         ...       ...
165  Analysis     VIT-B1-C   0.0   74.10    VIT-B1-C     74.10
166  Analysis     VIT-B2-C   0.0   90.43    VIT-B2-C     90.43
167  Analysis     VIT-B3-C   0.0   77.80    VIT-B3-C     77.80
168  Analysis      VIT-C-C   0.0  116.84     VIT-C-C    116.84
169  Analysis    VIT-D2-D3   0.0  258.38   VIT-D2-D3    258.38
170  Analysis    WATER-ACT   0.0   36.80   WATER-ACT     36.80
171  Analysis        YEAST   0.0    2.61       YEAST      2.61
172  Analysis           YM   0.0    5.22          YM      5.22
173  Analysis   YM-2DPETRI   0.0    9.01  YM-2DPETRI      9.01
174  Analysis     YM-AIR-C   0.0    5.22    YM-AIR-C      5.22
175  Analysis      YM-OSMO   0.0   12.92     YM-OSMO     12.92
176  Analysis     YM-PETRI   0.0    5.22    YM-PETRI      5.22
177        NaN         NaN   NaN     NaN  ACID-TITRA     16.90
178        NaN         NaN   NaN     NaN  COLI-M3-BG      5.72
179        NaN         NaN   NaN     NaN  COLI-M5-BG      7.22
180        NaN         NaN   NaN     NaN  COLI-MW-BG      8.70
181        NaN         NaN   NaN     NaN  EC-MPN3-EC      5.72
182        NaN         NaN   NaN     NaN  EC-MPN3-EM      5.72
183        NaN         NaN   NaN     NaN  EC-MPN3-IM      5.72
184        NaN         NaN   NaN     NaN  EC-MPNW-EC      8.70
185        NaN         NaN   NaN     NaN  EC-MPNW-EM      8.70
186        NaN         NaN   NaN     NaN  EC-MPNW-IM      8.70
187        NaN         NaN   NaN     NaN   HLAC-M3-C     17.10
188        NaN         NaN   NaN     NaN  L-G-CNF-ID     18.62
189        NaN         NaN   NaN     NaN  LMONO-CNF2     18.62
190        NaN         NaN   NaN     NaN    LSP-CNF2     14.98
191        NaN         NaN   NaN     NaN  LSP-CNFID7     37.87
192        NaN         NaN   NaN     NaN   LSP-PCR-C     14.82
193        NaN         NaN   NaN     NaN  SALMO-CN44     28.00
194        NaN         NaN   NaN     NaN  SALMO-CNF5     13.95

[195 rows x 6 columns]

In [167]:
dfResult['pricematch'] = np.where((dfResult['Price'] == dfResult['PriceJDE']), 'Match', 'Difference')

In [168]:
dfResult
dfResult= dfResult.loc[dfResult['pricematch'] == 'Difference']

In [169]:
dfResult

          type   testCodeL   Disc  Price   testCodeJ  PriceJDE  pricematch
60   Analysis    ID-ECCTFA  100.0   0.00         NaN       NaN  Difference
94   Analysis   LSP-UPENV4    0.0  13.43  LSP-UPENV4     13.79  Difference
177        NaN         NaN    NaN    NaN  ACID-TITRA     16.90  Difference
178        NaN         NaN    NaN    NaN  COLI-M3-BG      5.72  Difference
179        NaN         NaN    NaN    NaN  COLI-M5-BG      7.22  Difference
180        NaN         NaN    NaN    NaN  COLI-MW-BG      8.70  Difference
181        NaN         NaN    NaN    NaN  EC-MPN3-EC      5.72  Difference
182        NaN         NaN    NaN    NaN  EC-MPN3-EM      5.72  Difference
183        NaN         NaN    NaN    NaN  EC-MPN3-IM      5.72  Difference
184        NaN         NaN    NaN    NaN  EC-MPNW-EC      8.70  Difference
185        NaN         NaN    NaN    NaN  EC-MPNW-EM      8.70  Difference
186        NaN         NaN    NaN    NaN  EC-MPNW-IM      8.70  Difference
187        NaN         NaN    NaN    NaN   HLAC-M3-C     17.10  Difference
188        NaN         NaN    NaN    NaN  L-G-CNF-ID     18.62  Difference
189        NaN         NaN    NaN    NaN  LMONO-CNF2     18.62  Difference
190        NaN         NaN    NaN    NaN    LSP-CNF2     14.98  Difference
191        NaN         NaN    NaN    NaN  LSP-CNFID7     37.87  Difference
192        NaN         NaN    NaN    NaN   LSP-PCR-C     14.82  Difference
193        NaN         NaN    NaN    NaN  SALMO-CN44     28.00  Difference
194        NaN         NaN    NaN    NaN  SALMO-CNF5     13.95  Difference

In [170]:
opfname=limsFname[:-9]+'_Result.xlsx'
writer = pd.ExcelWriter(opfname)
dfResult.to_excel(writer,'Sheet1',index=False)
writer.save()